# Generated by Django 3.2.4 on 2021-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
