# Generated by Django 3.2.4 on 2021-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0002_alter_academic_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
