# Generated by Django 3.2.4 on 2021-06-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0005_alter_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passoutyr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
