# Generated by Django 3.2.4 on 2021-06-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0007_auto_20210627_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('paperCode', models.CharField(max_length=40)),
                ('creditPoint', models.CharField(max_length=30)),
                ('syllabus', models.FileField(upload_to='files/')),
                ('question', models.FileField(upload_to='files/')),
                ('studyNotes', models.FileField(upload_to='files/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.trade')),
                ('sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.semester')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.year')),
            ],
        ),
    ]
