# Generated by Django 3.2.4 on 2021-06-28 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0009_auto_20210627_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paperCode', models.CharField(max_length=40)),
                ('creditPoint', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='creditPoint',
        ),
        migrations.RemoveField(
            model_name='study',
            name='paperCode',
        ),
        migrations.RemoveField(
            model_name='study',
            name='question',
        ),
        migrations.RemoveField(
            model_name='study',
            name='studyNotes',
        ),
        migrations.RemoveField(
            model_name='study',
            name='syllabus',
        ),
        migrations.CreateModel(
            name='Sellybus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellybus', models.FileField(upload_to='files/')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.FileField(upload_to='files/')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Metarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.FileField(upload_to='files/')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='study',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collageapp.subject'),
        ),
    ]
