# Generated by Django 3.2.4 on 2021-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0010_auto_20210628_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='creditPoint',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='paperCode',
        ),
        migrations.AddField(
            model_name='study',
            name='creditPoint',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='paperCode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
