# Generated by Django 3.2.4 on 2021-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0011_auto_20210628_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
