# Generated by Django 3.2.4 on 2021-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0012_question_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarial',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
