# Generated by Django 3.2.4 on 2021-06-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0013_metarial_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjectcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
